In [2]:
# SVM code
import pandas as pd
import numpy as np
har=pd.read_csv("C:/Dataset//train.csv")

independent=har.drop(["Activity","subject"],axis=1)
independent
corr_matrix=independent.corr().abs()
upper=corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(np.bool))
to_drop=[column for column in upper.columns if any(upper[column]>0.70)]
len(to_drop)
X_train=independent.drop(independent[to_drop],axis=1)
y_train=pd.DataFrame(har[['Activity']])
replace_map = {'Activity': {'LAYING': 0, 'SITTING': 1, 'STANDING': 2, 'WALKING': 3,
                                  'WALKING_DOWNSTAIRS': 4, 'WALKING_UPSTAIRS': 5}} 
labels = y_train['Activity'].astype('category').cat.categories.tolist()
replace_map_comp = {'Activity' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

print(replace_map_comp)
y_train.replace(replace_map_comp, inplace=True)
y_train.iloc[52]
y_train
test=pd.read_csv("C:/Dataset/test.csv")
independent_test=test.drop(["Activity","subject"],axis=1)
X_test=independent_test.drop(independent_test[to_drop],axis=1)
X_test
y_test=pd.DataFrame(test[['Activity']])
replace_map = {'Activity': {'LAYING': 0, 'SITTING': 1, 'STANDING': 2, 'WALKING': 3,
                                  'WALKING_DOWNSTAIRS': 4, 'WALKING_UPSTAIRS': 5}} 
labels = y_test['Activity'].astype('category').cat.categories.tolist()
replace_map_comp = {'Activity' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

print(replace_map_comp)
y_test.replace(replace_map_comp, inplace=True)
y_train1 = pd.DataFrame(y_train['Activity'])

ytr1 = {1: 1, 2:0,3:0,4:0,5:0,6:0} 
y_train1.Activity = [ytr1[item] for item in y_train1.Activity] 


print(y_train1) 

y_train1 = y_train[["Activity"]].to_numpy()
y_train11=y_train.to_numpy()

from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train11)

y_predtrain1 = svclassifier.predict(X_train)

y_predtrain1

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train1,y_predtrain1))


print(classification_report(y_predtrain1,y_train1))

y_predtest1 = svclassifier.predict(X_test)

print(confusion_matrix(y_test,y_predtest1))

print(classification_report(y_predtest1,y_test))


{'Activity': {'LAYING': 1, 'SITTING': 2, 'STANDING': 3, 'WALKING': 4, 'WALKING_DOWNSTAIRS': 5, 'WALKING_UPSTAIRS': 6}}
{'Activity': {'LAYING': 1, 'SITTING': 2, 'STANDING': 3, 'WALKING': 4, 'WALKING_DOWNSTAIRS': 5, 'WALKING_UPSTAIRS': 6}}
      Activity
0            0
1            0
2            0
3            0
4            0
...        ...
7347         0
7348         0
7349         0
7350         0
7351         0

[7352 rows x 1 columns]


C:\Users\Trang Tran\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[1407    0    0    0    0    0]
 [   0 1169  117    0    0    0]
 [   0   96 1278    0    0    0]
 [   0    0    0 1224    1    1]
 [   0    0    0    0  982    4]
 [   0    0    0    1    2 1070]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1407
           2       0.91      0.92      0.92      1265
           3       0.93      0.92      0.92      1395
           4       1.00      1.00      1.00      1225
           5       1.00      1.00      1.00       985
           6       1.00      1.00      1.00      1075

    accuracy                           0.97      7352
   macro avg       0.97      0.97      0.97      7352
weighted avg       0.97      0.97      0.97      7352

[[537   0   0   0   0   0]
 [  0 418  70   0   0   3]
 [  0  48 484   0   0   0]
 [  0   0   0 491   3   2]
 [  0   0   0   7 395  18]
 [  0   0   2  36  34 399]]
              precision    recall  f1-score   support

           1       1.00      1.00      1